"""
This question is asked by Google. You are given two strings, 
s and t which only consist of lowercase letters. 
t is generated by shuffling the letters in s as well as potentially 
adding an additional random character. Return the letter that was 
randomly added to t if it exists, otherwise, return ’‘.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''
"""

def spotTheDifference(s: str, t: str) -> str:
  # Time: O(n+m)
  # Space: O(n)
  countLetters = dict()
  
  for c in s:
    if c not in countLetters:
      countLetters[c] = 0
    
    countLetters[c] += 1
  
  for c in t:
    if c in countLetters:
      countLetters[c] -= 1

      if countLetters[c] == 0:
        del countLetters[c]

    else:
      return c
  
  return ""

assert spotTheDifference("foobar", "barfoot") == "t"
assert spotTheDifference("ide", "idea") == "a"
assert spotTheDifference("coding", "ingcod") == ""
assert spotTheDifference("", "y") == "y"

print("Passed all tests!")


def spotTheDifference(s: str, t: str) -> str:
  # Time: O(n+m)
  # Space: O(1)
  sumASC_S = 0
  sumASC_T = 0
  
  for c in s:
    sumASC_S += ord(c)
  
  for c in t:
    sumASC_T += ord(c)
  
  return "" if sumASC_T-sumASC_S == 0 else chr(sumASC_T-sumASC_S)

assert spotTheDifference("foobar", "barfoot") == "t"
assert spotTheDifference("ide", "idea") == "a"
assert spotTheDifference("coding", "ingcod") == ""
assert spotTheDifference("", "y") == "y"

print("Passed all tests!")